name: Bug Report
description: Report a bug or issue with Flutter Terminal Helper
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Open terminal
        2. Press Ctrl+Space
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Tell us what you expected
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Tell us what actually happened
    validations:
      required: true

  - type: input
    id: vscode-version
    attributes:
      label: VSCode Version
      description: What version of VSCode are you using?
      placeholder: e.g., 1.85.0
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      description: What version of Flutter Terminal Helper?
      placeholder: e.g., 0.0.1
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please copy and paste any relevant log output
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, error messages, etc.
